/**
 * Copyright 2018 Dingfan Zhao
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.chatbot.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.mifos.chatbot.client.model.GetInterestRateChartsCurrency;
import org.mifos.chatbot.client.model.GetInterestRateChartsTemplatePeriodTypes;
import java.io.IOException;

/**
 * GetInterestRateChartsChartSlabs
 */

public class GetInterestRateChartsChartSlabs {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("periodTypes")
  private GetInterestRateChartsTemplatePeriodTypes periodTypes = null;

  @SerializedName("fromPeriod")
  private Integer fromPeriod = null;

  @SerializedName("annualInterestRate")
  private Integer annualInterestRate = null;

  @SerializedName("currency")
  private GetInterestRateChartsCurrency currency = null;

  public GetInterestRateChartsChartSlabs id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetInterestRateChartsChartSlabs periodTypes(GetInterestRateChartsTemplatePeriodTypes periodTypes) {
    this.periodTypes = periodTypes;
    return this;
  }

   /**
   * Get periodTypes
   * @return periodTypes
  **/
  @ApiModelProperty(value = "")
  public GetInterestRateChartsTemplatePeriodTypes getPeriodTypes() {
    return periodTypes;
  }

  public void setPeriodTypes(GetInterestRateChartsTemplatePeriodTypes periodTypes) {
    this.periodTypes = periodTypes;
  }

  public GetInterestRateChartsChartSlabs fromPeriod(Integer fromPeriod) {
    this.fromPeriod = fromPeriod;
    return this;
  }

   /**
   * Get fromPeriod
   * @return fromPeriod
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getFromPeriod() {
    return fromPeriod;
  }

  public void setFromPeriod(Integer fromPeriod) {
    this.fromPeriod = fromPeriod;
  }

  public GetInterestRateChartsChartSlabs annualInterestRate(Integer annualInterestRate) {
    this.annualInterestRate = annualInterestRate;
    return this;
  }

   /**
   * Get annualInterestRate
   * @return annualInterestRate
  **/
  @ApiModelProperty(example = "6", value = "")
  public Integer getAnnualInterestRate() {
    return annualInterestRate;
  }

  public void setAnnualInterestRate(Integer annualInterestRate) {
    this.annualInterestRate = annualInterestRate;
  }

  public GetInterestRateChartsChartSlabs currency(GetInterestRateChartsCurrency currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public GetInterestRateChartsCurrency getCurrency() {
    return currency;
  }

  public void setCurrency(GetInterestRateChartsCurrency currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInterestRateChartsChartSlabs getInterestRateChartsChartSlabs = (GetInterestRateChartsChartSlabs) o;
    return Objects.equals(this.id, getInterestRateChartsChartSlabs.id) &&
        Objects.equals(this.periodTypes, getInterestRateChartsChartSlabs.periodTypes) &&
        Objects.equals(this.fromPeriod, getInterestRateChartsChartSlabs.fromPeriod) &&
        Objects.equals(this.annualInterestRate, getInterestRateChartsChartSlabs.annualInterestRate) &&
        Objects.equals(this.currency, getInterestRateChartsChartSlabs.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, periodTypes, fromPeriod, annualInterestRate, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInterestRateChartsChartSlabs {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    periodTypes: ").append(toIndentedString(periodTypes)).append("\n");
    sb.append("    fromPeriod: ").append(toIndentedString(fromPeriod)).append("\n");
    sb.append("    annualInterestRate: ").append(toIndentedString(annualInterestRate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

